[package]
name = "control-plane"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
control-auth = { path = "../control-auth" }
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
service-auth = { path = "../service-auth" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
transport-security = { path = "../transport-security" }

[dev-dependencies]
axum-server.workspace = true
rcgen = "0.14.8"
